title: Clara Kelley # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior in Computer Science - HCI at Stanford 
  <br><br>
  1st Year Masters in Computer Science at Stanford
  <br><br>
  Seeking internship for 2020
  <br><br>
  <a href="http://drive.google.com/file/d/1spiiAkzTA5I-neS2YmgMLfgi70DOnIMP">View my resume</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
